# Generated by Django 5.0.2 on 2024-03-12 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="city",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="street_address",
        ),
    ]
