# Generated by Django 5.0.2 on 2024-03-17 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_accounts", "0002_remove_useraccount_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="account_no",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
